services:
  database:
    image: mysql:9.3.0
    volumes:
      - db_dados:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: here123
      MYSQL_DATABASE: wordpress
    networks:
      - wordpress-overlay
    deploy:
      placement:
        constraints:
          - "node.labels.db==true"
      replicas: 1


  frontend:
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: user_db
      WORDPRESS_DB_PASSWORD: here123
      WORDPRESS_DB_NAME: db_word
    networks:
      - wordpress-overlay
    deploy:
      replicas: 3


volumes:
  db_dados:
  wordpress_data:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.57.11,rw,nolock"
      device: ":/srv/wordpress"


networks:
  wordpress-overlay:
    driver: overlay
    attachable: true
    name: wordpress-verlay
    driver_opts:
      encrypted: "true"
