networks:
  monitoring:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1


volumes:
  prometheus_data: {}
  alertmanager_data: {}


services:

  alertsmiddle:
    build:
      context: .
    hostname: 'alertsMiddle'
    ports:
      - 8000:8000
    depends_on:
      - metricsFATcherHog
      - lightAboveTheProblems
    networks:
      monitoring:
        ipv4_address: 172.19.0.3
    volumes:
      - ./appJsonStore:/app/dump_data


  dockadvisor:
#    container_name: cadvisor
    hostname: 'dockadvisor'
    image: gcr.io/cadvisor/cadvisor:v0.51.0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
    ports:
      - "8080:8080"
    restart: always
    networks:
      - monitoring


  metricsFATcherHog:
#    container_name: prometheus
    hostname: 'metricsFATcherHog'
    image: prom/prometheus:v3.7.3
    ports:
      - "9090:9090"
    restart: always
    depends_on:
      - dockadvisor
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    networks:
      - monitoring


  lightAboveTheProblems:
#    container_name: alertmanager
    hostname: 'lightAboveTheProblems'
    image: prom/alertmanager:v0.29.0
    ports:
      - "9093:9093"
    restart: always
    depends_on:
      - metricsFATcherHog
    volumes:
      - ./alertmanager:/etc/alertmanager
    networks:
      - monitoring
