global:
  scrape_interval: 1s
  evaluation_interval: 2s
 
rule_files:
  - alertmgr.rules.yml
 
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: ['lightAboveTheProblems:9093']
 
scrape_configs:
#  - job_name: metricsFATcherHog
  - job_name: 'dockadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['dockadvisor:8080']
